### ISSUE TITLE
rubriken konstig om man inte har strata

### ISSUE THREAD

**Issue by eribul** [cancercentrum/incasurv#19]
Rubriken rumphuggen "Relativ överlevnad per"

**Comment by Cstaf** [comment]
Kan inte återskapa problemet i rapporten efter övergången till highcharts.

**Comment by eribul** [comment]
Hm, säker? Detta rörde ju `incasurv` där jag tror att jag kan ha schabblat till det lite då jag ändrade en hel del i skripten. HC användes väl bara i `HH_survival` (inte i `incasurv`).

**Comment by Cstaf** [comment]
Det stämmer, trodde jag var inne på HH_survival och inte incasurv.
